package dao.connection;


import dao.DaoException;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class DaoConnection implements AutoCloseable{
    private Connection connection;
    private boolean isTransaction;

    public DaoConnection(Connection connection) {
        this.connection = connection;
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
        try {
            return connection.prepareStatement(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            throw new DaoException("Can't prepare statement with auto generated keys", e);
        }
    }

    public PreparedStatement prepareStatement(String sql) {
        try {
            return connection.prepareStatement(sql);
        } catch (SQLException e) {
            throw new DaoException("Can't prepare statement", e);
        }
    }

    public Statement createStatement() {
        try {
            return connection.createStatement();
        } catch (SQLException e) {
            throw new DaoException("Can't create statement", e);
        }
    }

    public void setIsTransaction(boolean isInTransaction) {
        this.isTransaction = isInTransaction;
        try {
            connection.setAutoCommit(!isInTransaction);
        } catch (SQLException e) {
            throw new DaoException("Can't set is-in-transaction", e);
        }
    }

    public void commit() {
        if (!isTransaction) {
            throw new DaoException("Can't commit: Is not in transaction");
        }
        try {
            connection.commit();
        } catch (SQLException e) {
            throw new DaoException("Can't commit", e);
        }
    }

    public void rollback() {
        if (!isTransaction) {
            throw new DaoException("Can't rollback: Is not in transaction");
        }
        try {
            connection.rollback();
        } catch (SQLException e) {
            throw new DaoException("Can't rollback", e);
        }
    }

    public void close() {
        try {
            if (!isTransaction) {
                connection.close();
            }
        } catch (SQLException e) {
            throw new DaoException("Can't close dao.connection", e);
        }
    }
}
